config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  root 'users#new'
  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :favorites, only: [:create, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :image, :content , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, length: { minimum: 6 }
    has_many :feeds
    mount_uploader :picture, ImageUploader

    has_many :favorites, dependent: :destroy
    has_many :favorite_feeds, through: :favorites, source: :feed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_path, notice: "#{favorite.feed.user.name}さんの画像をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_path, notice: "#{favorite.feed.user.name}さんの画像をお気に入り解除しました"
  end

  def index
      @favorites = current_user.favorite_feeds.all
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[ show edit update destroy ]

  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
  end

  def edit
    unless current_user.email == @feed.user.email
      redirect_to feeds_path
            flash[:notice] = '他のユーザーの投稿を編集することはできません。'
    end
  end

  def create
    @feed = current_user.feeds.build(feed_params)

    respond_to do |format|
      if @feed.save
        ContactMailer.send_mail(@feed).deliver
        format.html { redirect_to feed_url(@feed) , notice: "Feed was successfully created."}
        format.json { render :show, status: :created, location: @feed }

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to feed_url(@feed), notice: "Feed was successfully updated." }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: "Feed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:content, :image, :image_cache, :send_mail)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
    else
        flash.now[:danger] = 'ログインに失敗しました'
        render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: %i[ show edit update destroy ]
    skip_before_action :login_required, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
        if current_user.id == @user.id
        else
            redirect_to user_path(@user.id)
            flash[:notice] = '他のユーザーのプロフィールを編集することはできません。'
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "情報を編集しました！"
            redirect_to user_path
        else
            render :edit
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password,:password_confirmation, :picture, :picture_cache)
    end

    def set_user
        @user = User.find(params[:id])
        redirect_to users_path, notice: "他者のアカウント情報は変更不可です" unless @user.name == current_user.name
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
    def choose_new_or_edit
        if action_name == 'new'
            confirm_feeds_path
        elsif action_name == 'edit'
            feed_path
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>お気に入り一覧</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>word</th>
      <th>user</th>
      <th colspan="0"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= image_tag favorite.image.url , size: "50x50" %></td>
        <td><%= favorite.content %></td>
        <td><%= favorite.user.name %></td>
        <td><%= link_to 'Show', favorite %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'Back', feeds_path %> |
<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= form.label :image %>
      <%= image_tag(feed.image.url) if feed.image && feed.image.url %>
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <div class="content_word">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
    <br>
      <%= form.hidden_field :content %>
      <p>本文:<%= @feed.content %></p>
    <br>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

  <h1>Feeds</h1>

  <table>
    <thead>
      <tr>
        <th>user</th>
        <th>word</th>
        <th>picture</th>
        <th colspan="0"></th>
      </tr>
    </thead>

    <tbody>
      <% @feeds.each do |feed| %>
        <tr>
          <td><%= feed.user.name %></td>
          <td><%= feed.content %></td>
          <td><%= image_tag feed.image.url, style:'width:350px;height:200px' if feed.image_url %></td>
          <td><%= link_to 'Show', feed %></td>

          <% if current_user.email == feed.user.email %>
            <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
            <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br><br>
  <%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>投稿者:</strong>
  <%= @feed.user.name %>
</p>

<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
</div>

  <% if current_user.email == @feed.user.email %>
    <td><%= link_to 'Edit' %>
  <% end %>
  <%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>
  <%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :picture %>
  <%= image_tag(@user.picture.url) if @user.picture && @user.picture.url %>
  <%= f.file_field :picture %>
  <%= f.hidden_field :picture_cache %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <div class="submit_record">
    <p><%= f.submit "内容変更" %></p>
  </div>
  <% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

    <% if @user.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %>prohibited this<%= @user.name %>from being saved:</h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
    </div>
    <% end %>
        <%= form_with(model:@user, local:true ) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :picture %>
        <%= picture_tag(@user.picture.url) if @user.picture && @user.picture.url %>
        <%= f.file_field :picture %>
        <%= f.hidden_field :picture_cache %>

        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
        <%= f.submit "Create my account" %>
    <% end %>

app/views/users/show.html.erb
  <h1><%= @user.name %>のページ</h1>
    <p>メールアドレス: <%= @user.email %></p>
    <p>
    <strong>画像:</strong>
    <%= image_tag @user.picture.url, style:'width:50px;height:50px'if @user.picture && @user.picture.url %>
    </p>

    <% if current_user.id == @user.id %>
    <%= link_to '編集', edit_user_path(@user), class:"link_button" %> |
    <% end %>

    <%= link_to '投稿', new_feed_path, class: "btn btn-info" %>
    <%= link_to '投稿一覧', feeds_path %>

    <%= link_to 'お気に入り画像一覧へ', favorites_path %>